[package]
name = "roseconv"
version = "0.1.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]

[dependencies]
clap = {version = "^2", features = ["yaml"]}
error-chain = "^0.11"
roselib = {path = "../rose-lib"}
