[package]
name = "vfs_extractor"
version = "2.0.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]

[dependencies]
clap = {version = "~2.21.0", features = ["yaml"]}
roselib = { path = "../rose-lib" }
