[package]
name = "vfs_tool"
version = "1.0.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]

[dependencies]
clap = {version = "2.29", features = ["yaml"]}
roselib = { path = "../rose-lib" }
